### PR TITLE
Add off-nominal roll capability to dea_check.

### PR DESCRIPTION
**Pull request by jzuhone**
A recent proposed update to the 1DEAMZT model has off-nominal roll incorporated (https://github.com/sot/chandra_models/pull/23). These changes incorporate the off-nominal roll into the DEA model validation.

### CODE REVIEW

**Comment by taldcroft** [comment]
Probably worth updating `VERSION` to 1.1.  Otherwise looks good.

**Comment by taldcroft** [comment]
@jzuhone - Are you planning to do the Ska.DBI => HDF5 (cmd_states.fetch_states) migration here or in a separate PR?

**Comment by jzuhone** [comment]
@taldcroft I can do either--what is your preference?

**Comment by taldcroft** [comment]
Separate will be cleaner.  Same changes should apply to PSMC, DPA, and ACIS FP checkers.  I'm sure you've noticed plenty of commonality among those scripts, so there would be benefit to refactoring a bunch of that out to a common package (e.g. acis_thermal_check).  But of course that does take time.

**Comment by jeanconn** [comment]
When I looked at this a while back, I noted that while the switch to fetch
the cmd_states from HDF5 instead of sybase is trivial in get_states() in
these validation tools,
changing the overall logic to get a reasonable state0 and build the
expected states from available commands (without any dependence on Sybase)
was not as trivial.

​

**Comment by taldcroft** [comment]
OK, I looked at the code again and agree that there are additional Sybase dependencies which are trickier to remove.  The right way forward is to use the kadi database of commands, which is essentially all the onboard commands that have actually run or are approved to run.  The only problem with that right now is that kadi doesn't yet include non-load commands like when SCS-107 runs.

**Comment by jeanconn** [comment]
The starcheck implementation is not *horrible*:

https://github.com/sot/starcheck/blob/master/starcheck/calc_ccd_temps.py

**Comment by taldcroft** [comment]
I forgot about the starcheck implementation, which indeed looks fine.  It is worth noting that the "3 day" interval is there to ensure that the ACA CCD model pseudo-node has time to equilibrate from the initial (incorrect) starting value.

**Comment by jeanconn** [comment]
@jzuhone May I merge and install this PR to /proj/sot/ska/share/dea at any time or do we need to coordinate?

**Comment by jzuhone** [comment]
@jeanconn I think we should be good with merging this in.

**Comment by jeanconn** [comment]
Merged.  I note that this is not compatible with the previous model spec (that wasn't immediately obviously to me from the code changes).  I don't see where it would be a problem though.

**Comment by jzuhone** [comment]
@jeanconn thanks for merging this in. Can we get the new version installed into `/proj/sot/ska/share/dea`?

**Comment by jeanconn** [comment]
Sure.  Formally, I think I need your double-check on and approval of #8 before I merge that and then install.

**Comment by jeanconn** [comment]
New version installed.

**Pull request merged**
