### PR TITLE
Make the CCD count / SIM-Z plot and the temperature plot have the same axis width

### PR DESCRIPTION
**Pull request by jzuhone**
These changes align the axes of the first and second plots on the 1DEAMZT temperature check page so that it's easier to look straight down from one plot to the other and see the state at the same date/time. 

Before example:
http://cxc.cfa.harvard.edu/acis/DEA_thermPredic/DEC2815/oflsc/

After example:
http://cxc.cfa.harvard.edu/acis/tmp/fix_width/

If/when these changes are accepted I'd like to do the same for the other temperature model checker tools.

### CODE REVIEW

**Comment by jeanconn** [comment]
Looks great.  Maybe add a comment? (that depends on audience, but for me, I might not remember what the intent was here without re-working-out the algebra).

**Comment by taldcroft** [comment]
Looks good, though you need to bump the version to 1.1.1. This could be considered a bug fix if we retroactively make it a requirement that plots lines up.

There is still a question of factoring out stuff like this to a common base module, since presumably the same change would be nice for DPA,psmc, and ACIS fp.  But this isolated change is certainly fine.

**Comment by jzuhone** [comment]
Ok, I've added the comment and bumped the version number.

**Comment by jzuhone** [comment]
Hi, I was wondering if there was anything else I needed to add to this before getting it merged in?

**Comment by taldcroft** [comment]
@jzuhone - sorry, this fell off the radar.  I'm good with the content.  Since checking DEA temperature is formally part of load review now, this needs to be presented quickly at the next load review.  It's a teeny change but still needs to go through the process.  You can ask your ACIS cohorts for more details.

**Comment by richardjedgar** [comment]
@jzuhone : I'm good with this. Thanks for making it happen.

**Pull request merged**
